version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - .dev_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d postgres"]
      interval: 5s
      start_period: 100s

  web:
    command: sh -c "sh migrate.sh && sh entrypoint.sh"
    build: ./src
    image: django-k8s:latest
    env_file:
      - ./src/.env
    ports:
      - "8005:8002"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .dev_media:/code/media

volumes:
  .dev_media:
  .dev_postgres_data:

