version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - .prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d postgres"]
      interval: 5s
      start_period: 100s

  web:
    command: sh -c "sh migrate.sh && sh entrypoint.sh"
    build: ./src
    image: django-k8s:latest
    env_file:
      - ./src/.env
    ports:
      - "8005:8002"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .prod_www-data:/www-data/web

  nginx:
    build:
      context: ./nginx
    #restart: always
    depends_on:
      - web
    ports:
      - "8080:80"
    environment:
      - APP_HOST=web
    volumes:
      - .prod_www-data:/www-data/web

volumes:
  .prod_postgres_data:
  .prod_www-data:

