version: "3.9"

services:
  db:
    image: postgres:alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d postgres"]
      interval: 5s
      start_period: 60s

  web:
    command: sh -c "sh /code/migrate.sh && sh /code/entrypoint.sh"
    build: ./src
    image: django-k8s:latest
    env_file:
      - ./src/.env
    ports:
      - "8005:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
