apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  ports:
    - port: 80
  selector:
    app: django
    tier: app
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: app
    spec:
      volumes:
        - name: django-app-data
          persistentVolumeClaim:
            claimName: django-app-pvc
      containers:
        - image: django-app:latest
          imagePullPolicy: Never
          name: app
          volumeMounts:
            - name: django-app-data
              mountPath: /www-data/web
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret_key
            - name: DJANGO_SUPERUSER_EMAIL
              value: admin_user@ex.com
            - name: DJANGO_SUPERUSER_USERNAME
              value: admin_user
            - name: DJANGO_SUPERUSER_PASSWORD
              value: "123"
            - name: POSTGRES_HOST
              value: django-postgres
            - name: DJANGO_DEBUG
              value: "False"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_NAME
              value: django_db
            - name: POSTGRES_USER
              value: django_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password

        - image: django-nginx:latest
          imagePullPolicy: Never
          name: nginx
          ports:
            - containerPort: 80
              name: nginx
          volumeMounts:
            - name: django-app-data
              mountPath: /www-data/web
          env:
            - name: APP_HOST
              value: "127.0.0.1"
