# Generated by Django 4.2.14 on 2024-08-08 20:48

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=1000)),
                (
                    "image",
                    models.ImageField(upload_to=posts.models._generate_path_to_image),
                ),
            ],
        ),
    ]
